### ISSUE TITLE
'Library' object has no attribute 'assignment_tag'

### ISSUE THREAD

**Issue by ghost** [lazybird/django-carton#3]
carton_tags.py keep this error

thanks

**Comment by BrealX** [comment]
... and again the same error, but now it's caused by deprecation and removing "assignment_tag" from Django > 1.9. I've solved it this way:

In carton_tags.py:

@register.simple_tag(takes_context=True, name=CART_TEMPLATE_TAG_NAME)
def get_cart(context, session_key=None, cart_class=Cart):
    """
    Make the cart object available in template.

    Sample usage::

        {% load carton_tags %}
        {% get_cart as cart %}
        {% for product in cart.products %}
            {{ product }}
        {% endfor %}
    """
    request = context['request']
    return cart_class(request.session, session_key=session_key)

Work fine with Django 2.0.3
